[tool.poetry]
name = "claude-mcp-skeleton"
version = "0.1.0"
description = ""
authors = ["Kirk Byers <ktbyers@twb-tech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mcp = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
